AWSTemplateFormatVersion: "2010-09-09"
Description: Infraestructura para desplegar Flutter Web (BTG Fondos)

Resources:
  FlutterWebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: btg-fondos-flutter-web
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FlutterWebBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Join ["", ["arn:aws:s3:::", !Ref FlutterWebBucket, "/*"]]
