default_platform(:ios)

platform :ios do
  desc "Compilar y subir a TestFlight"
  lane :deploy_beta do
    increment_build_number(
      xcodeproj: "Runner.xcodeproj"
    )
    build_ios_app(
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end