name: CI/CD Flutter App

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_app

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - run: flutter pub get
      - run: flutter test
      - run: cd android && bundle install && bundle exec fastlane deploy_beta

  build_ios:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: my_app

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"

      - run: flutter pub get
      - run: flutter test
      - run: cd ios && bundle install && bundle exec fastlane deploy_beta
